# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-pool
  namespace: metallb-system
spec:
  addresses:
  # 각 worker 노드 ip 확인 후 적용
  - 34.47.73.215/32    # worker-1
  - 34.50.50.244/32    # worker-2
#  - 34.64.220.198/32   # worker-3
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - external-pool